version: '3'
services:
  app:
    image: your-dockerhub-username/nampa_neighbor_network:latest
    restart: unless-stopped
    env_file:
      - nampa_neighbor_network-env
    ports:
      - "3000:3000"
